### ISSUE TITLE
Error when exporting using the DaztoBlender plugin

### ISSUE THREAD

**Issue by mcographics** [daz3d/DazToBlender#217]
![0041eba3981383ef37aad87e4d8ba1](https://github.com/user-attachments/assets/caba84a2-201f-43b8-9fc9-6f2d64b190af)
![35814229fef9a76e30a1a79692809b](https://github.com/user-attachments/assets/f965380e-8c44-4c1d-af91-75803ef552d7)

im not sure if im doing something wrong but im not sure how to fix this, i did a clean install of the plugin, used REVO to wipe it out, and redownloaded the latests from here on github, but im not sure why this error persists..

**Comment by danielbui78** [comment]
Bug fixed in Hotfix 107 (https://github.com/daz3d/DazToBlender/releases/tag/2024.2.17-hotfix-107)  you can download from the Release page now, it should be uploaded to our DIM service in a few days.

**Comment by mcographics** [comment]
![Capture](https://github.com/user-attachments/assets/7836fabb-1c6c-46c8-96a3-1e54460cbc25)
![Capture2](https://github.com/user-attachments/assets/a420b1e6-62ff-4b28-a624-b1e427057fcf)


Downloaded the hotfix, cleaned out previous, installed hot fix, reloaded previous project, issue persists. So, I decided to load up a blank genesis character, AND same thing persists..

**Comment by mcographics** [comment]
what else do you recommend i should do if it not working ?

**Comment by danielbui78** [comment]
screenshot shows you are running version 2024 v2.15.105 which is the version prior to the latest update.  The latest update should show version 2024 v2.17.107.  You need to correctly install the plugin using the manual installation instructions.

**Comment by mcographics** [comment]
The current version is properly installed now, the issue still persists.

![11111](https://github.com/user-attachments/assets/2ad9cb29-2517-4b9b-9028-e6d5efb126e1)
![image](https://github.com/user-attachments/assets/b7018f47-d005-4157-8be2-fcf069f17cd3)

**Comment by danielbui78** [comment]
Thanks, we can now identify the problem file: please upload the "B_FBX.fbx" that is in the error message above and post a link to it here.

Please also post your log.txt file here.  You can find it at  `%APPDATA%\DAZ 3D\Studio4\log.txt`.

**Comment by mcographics** [comment]
the problem is there is no file in the directory when i go there, the folder is empty. 
[log.txt](https://github.com/user-attachments/files/17929074/log.txt)

**Comment by mcographics** [comment]
please log file :)

**Comment by danielbui78** [comment]
Thank you, that was very helpful information.  I will work on a script to help debug file write issues on your system.  It may take a few days.

**Comment by danielbui78** [comment]
Please download, unzip and double-click this Daz Script.  It should create a `diagnostic_log.txt` file in the Intermediate folder where the B_FBX.fbx should have been written.  Please upload that file or let me know if there was an error when running it.

[bridge_troubleshooter.dsa.zip](https://github.com/user-attachments/files/17929911/bridge_troubleshooter.dsa.zip)

**Comment by mcographics** [comment]
it asks me where to save but the button says open, it doesnt save

**Comment by danielbui78** [comment]
Can you please open a support ticket here: https://bugs.daz3d.com/hc/en-us/requests/new
I have reviewed your case with the customer support team and they will contact me when they receive your ticket, just copy and paste the URL for this github issue in your support request to them.

**Comment by mcographics** [comment]
bit late sorry, I've just now submitted a ticket and the link to this here, hopefully they still reach out to you.
